### ISSUE TITLE
How to get probabilities of answers?

### ISSUE THREAD

**Issue by 25icecreamflavors** [OFA-Sys/OFA#160] opened 2022-07-13 20:26 UTC
I used models like LXMERT and Visual Bert for VQA task on COCO dataset and was able to get a list of probabilities for possible answers (there are limited number of them). How can I get probabilities here? I would like to get them with the answer: (answer, probabilities). Not just a confidence score for a one answer, but a list of probabilities distribution for all possible answers.

**Comment by logicwong** [comment] 2022-07-14 02:40
Duplicate of #72 and #84

**Comment by JustinLin610** [comment] 2022-07-28 12:42
check https://github.com/OFA-Sys/OFA/blob/feature/add_transformers/transformers/src/transformers/models/ofa/modeling_ofa.py , the method `get_normalized_probs` should meet your demand.

**Closed** 2022-08-12 15:55 UTC
