### ISSUE TITLE
Text-to-Image Generation Code Example

### ISSUE THREAD

**Issue by AI-EnabledSoftwareEngineering-AISE** [OFA-Sys/OFA#63] opened 2022-04-03 05:40 UTC
Thank you for your awesome project. I look at your repository but I could not find any example for Text-To-Image generation(I mean like what you have provided in google Colab for other tasks).

Could you please provide a code example that just generates an image from the input text?

**Comment by jxst539246** [comment] 2022-04-06 04:02
Hi, we have uploaded a code example [image_gen_example.py](https://github.com/OFA-Sys/OFA/blob/main/run_scripts/image_gen/image_gen_example.py).  
It will start a toy server waiting for the input text and then generate images.
We didn't provide the example in google Colab as the image generation task requires a large amount of memory, but it seems like Colab cannot guarantee to provide a GPU with enough memory.

**Comment by AI-EnabledSoftwareEngineering-AISE** [comment] 2022-04-06 06:40
Thanks for your helpful response I will try to run the code on our server and share the results with you.

**Comment by AI-EnabledSoftwareEngineering-AISE** [comment] 2022-04-06 09:06
@jxst539246 Thank you for your help.

I tried to run your code but I get `Key 'eval_clip' not in 'ImageGenConfig'` Error for both image_gen_base_best and image_gen_large_best model. I will paste the error here!

```
ConfigKeyError Traceback (most recent call last)
/tmp/ipykernel_13534/3460324211.py in
13 models, cfg, task = checkpoint_utils.load_model_ensemble_and_task(
14 utils.split_paths('./checkpoints/image_gen_base_best.pt'),
---> 15 arg_overrides=overrides
16 )
17 task.cfg.sampling_times = 2

~/.conda/envs/ofa/lib/python3.7/site-packages/fairseq/checkpoint_utils.py in load_model_ensemble_and_task(filenames, arg_overrides, task, strict, suffix, num_shards, state)
430
431 if task is None:
--> 432 task = tasks.setup_task(cfg.task)
433
434 if "task_state" in state:

~/.conda/envs/ofa/lib/python3.7/site-packages/fairseq/tasks/init.py in setup_task(cfg, **kwargs)
37 if task_name and task_name in TASK_DATACLASS_REGISTRY:
38 dc = TASK_DATACLASS_REGISTRY[task_name]
---> 39 cfg = merge_with_parent(dc(), cfg)
40 task = TASK_REGISTRY[task_name]
41

~/.conda/envs/ofa/lib/python3.7/site-packages/fairseq/dataclass/utils.py in merge_with_parent(dc, cfg, remove_missing)
488 del cfg[k]
489
--> 490 merged_cfg = OmegaConf.merge(dc, cfg)
491 merged_cfg.dict["_parent"] = cfg.dict["_parent"]
492 OmegaConf.set_struct(merged_cfg, True)

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/omegaconf.py in merge(*others)
319
320 with flag_override(target, "readonly", False):
--> 321 target.merge_with(*others[1:])
322 turned_readonly = target._get_flag("readonly") is True
323

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/basecontainer.py in merge_with(self, *others)
329 self._merge_with(*others)
330 except Exception as e:
--> 331 self._format_and_raise(key=None, value=None, cause=e)
332
333 def _merge_with(

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
99 msg=str(cause),
100 cause=cause,
--> 101 type_override=type_override,
102 )
103 assert False

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
627 ex = type_override(str(cause))
628 ex.dict = copy.deepcopy(cause.dict)
--> 629 _raise(ex, cause)
630
631 object_type: Optional[Type[Any]]

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/_utils.py in _raise(ex, cause)
608 else:
609 ex.cause = None
--> 610 raise ex # set end OC_CAUSE=1 for full backtrace
611
612

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/basecontainer.py in merge_with(self, *others)
327 ) -> None:
328 try:
--> 329 self._merge_with(*others)
330 except Exception as e:
331 self._format_and_raise(key=None, value=None, cause=e)

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/basecontainer.py in _merge_with(self, *others)
345 other = _ensure_container(other)
346 if isinstance(self, DictConfig) and isinstance(other, DictConfig):
--> 347 BaseContainer._map_merge(self, other)
348 elif isinstance(self, ListConfig) and isinstance(other, ListConfig):
349 self.dict["_content"] = []

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/basecontainer.py in _map_merge(dest, src)
312 dest[key] = src._get_node(key)
313 else:
--> 314 dest[key] = src._get_node(key)
315
316 if src_type is not None and not is_primitive_dict(src_type):

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/dictconfig.py in setitem(self, key, value)
257 except AttributeError as e:
258 self._format_and_raise(
--> 259 key=key, value=value, type_override=ConfigKeyError, cause=e
260 )
261 except Exception as e:

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/base.py in _format_and_raise(self, key, value, cause, type_override)
99 msg=str(cause),
100 cause=cause,
--> 101 type_override=type_override,
102 )
103 assert False

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/_utils.py in format_and_raise(node, key, value, msg, cause, type_override)
627 ex = type_override(str(cause))
628 ex.dict = copy.deepcopy(cause.dict)
--> 629 _raise(ex, cause)
630
631 object_type: Optional[Type[Any]]

~/.conda/envs/ofa/lib/python3.7/site-packages/omegaconf/_utils.py in _raise(ex, cause)
608 else:
609 ex.cause = None
--> 610 raise ex # set end OC_CAUSE=1 for full backtrace
611
612

ConfigKeyError: Key 'eval_clip' not in 'ImageGenConfig'
full_key: eval_clip
reference_type=Optional[ImageGenConfig]
object_type=ImageGenConfig
```
Do you know how can I solve this error?

**Comment by jxst539246** [comment] 2022-04-07 05:44
The key 'eval_clip' has been removed in the previous updates. 
It seems like you need to fetch and update the main branch.

**Comment by skabongo2022** [comment] 2022-04-19 16:31
Hi @AI-EnabledSoftwareEngineering-AISE  did you manage to solve the problem ? 

@jxst539246 I'm using the latest version of master but still having the same issue. 

Thank you.

**Comment by jxst539246** [comment] 2022-04-20 03:54
@skabongo2022  I tried the example with the latest version of master again and didn't meet this issue...
Could you provide more details e.g. the full error or the python environment?

**Comment by skabongo2022** [comment] 2022-04-20 18:55
Hi @jxst539246 thank you for a quick reply. 

See belkow the env details that gives the error `ConfigKeyError: Key 'eval_clip' not in 'ImageGenConfig'
	full_key: eval_clip
	reference_type=Optional[ImageGenConfig]
	object_type=ImageGenConfig`
	
Note that the env bellow works fine with other tasks. 

FYI I created a new env with python 3.7.4 and everything works fine now but I still don't know for sure why the other env was not working.

```yml
name: ofa
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=py_0
  - ca-certificates=2020.10.14=0
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - decorator=4.4.2=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.2=py38_0
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py38_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgomp=11.2.0=h1d223b6_14
  - libllvm11=11.1.0=hf817b99_3
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libzlib=1.2.11=h166bdaf_1014
  - llvmlite=0.38.0=py38h38d86a4_1
  - ncurses=6.3=h9c3ff4c_0
  - numba=0.55.1=py38h4bf6c61_0
  - openssl=3.0.2=h166bdaf_1
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=22.0.4=pyhd8ed1ab_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.7.1=py_0
  - python=3.8.12=h0744224_3_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=2_cp38
  - pyzmq=19.0.2=py38he6710b0_1
  - readline=8.1=h46c0cb4_0
  - setuptools=62.0.0=py38h578d9bd_0
  - six=1.15.0=py_0
  - sqlite=3.37.1=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.3=he6710b0_3
  - zlib=1.2.11=h166bdaf_1014
  - pip:
    - absl-py==1.0.0
    - aiobotocore==2.2.0
    - aiohttp==3.8.1
    - aioitertools==0.10.0
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==20.3.0
    - bitarray==2.4.1
    - boto3==1.21.42
    - botocore==1.24.42
    - cachetools==5.0.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.1.2
    - colorama==0.4.4
    - cycler==0.11.0
    - cython==0.29.28
    - datasets==2.0.0
    - dill==0.3.4
    - einops==0.4.1
    - fairseq==1.0.0a0+355ffbe
    - filelock==3.6.0
    - fonttools==4.32.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - ftfy==6.0.3
    - google-auth==2.6.4
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - huggingface-hub==0.5.1
    - hydra-core==1.0.7
    - idna==3.3
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.0
    - jmespath==1.0.0
    - joblib==1.1.0
    - kiwisolver==1.4.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - nltk==3.7
    - numpy==1.22.3
    - oauthlib==3.2.0
    - omegaconf==2.0.6
    - opencv-python==4.5.5.64
    - packaging==21.3
    - pandas==1.4.2
    - pathos==0.2.8
    - pillow==9.1.0
    - portalocker==2.4.0
    - pox==0.3.0
    - ppft==1.6.6.4
    - protobuf==3.20.0
    - protobuf3-to-dict==0.1.5
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocoevalcap==1.2
    - pycocotools==2.0.4
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pyparsing==3.0.8
    - pytorch-lightning==1.6.0
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rouge-score==0.0.4
    - rsa==4.8
    - s3fs==2022.3.0
    - s3transfer==0.5.2
    - sacrebleu==2.0.0
    - sagemaker==2.86.2
    - smdebug-rulesconfig==1.0.1
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.4.1
    - timm==0.5.4
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchmetrics==0.7.3
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.1.1
    - wrapt==1.14.0
    - xxhash==3.0.0
    - yarl==1.7.2
    - zipp==3.8.0
```

**Comment by jxst539246** [comment] 2022-04-21 03:06
@skabongo2022 I think I found the cause of the problem. 
There is an argument "**remove_missing**" in the method **merge_with_parent**, which remove missing keys during loading ckpt.
`~/.conda/envs/ofa/lib/python3.7/site-packages/fairseq/dataclass/utils.py in merge_with_parent(dc, cfg, remove_missing)
488 del cfg[k]
489
--> 490 merged_cfg = OmegaConf.merge(dc, cfg)
491 merged_cfg.dict["_parent"] = cfg.dict["_parent"]
492 OmegaConf.set_struct(merged_cfg, True)`

The default value for **remove_missing** is **True** in the Fairseq library provided in the OFA repo.
However, in the official Fairseq repo, it has been changed to **False** in a recent [commit](https://github.com/pytorch/fairseq/commit/995c204337d16a6146a433cee360e5a5bfbc9a6f). That may cause the error.

**Closed** 2022-04-22 02:42 UTC
