### ISSUE TITLE
when i run run_scripts/caption/caption_train_stage1, i had some problems

### ISSUE THREAD

**Issue by cxy990729** [OFA-Sys/OFA#75] opened 2022-04-20 07:44 UTC
@logicwong Hi, thanks for the wonderful work. when i run run_scripts/caption/caption_train_stage1, i had some problems
That seems to be the problem：
 File "/data1/cxy/OFA/models/sequence_generator.py", line 480, in _generate
    assert step < max_len, f"{step} < {max_len}"
AssertionError: 16 < 16
How should I handle it？

2022-04-18 21:46:53 - progress_bar.py[line:274] - INFO: epoch 001:    491 / 70844 loss=3.702, loss_v1=0, loss_v2=0, nll_loss=1.589, ntokens=99.2, nsentences=8, sample_size=99.2, sample_size_v1=0, sample_size_v2=0, ppl=3.01, wps=92, ups=0.93, wpb=99.2, bsz=8, num_updates=490, lr=2.88201e-07, gnorm=8.633, clip=100, loss_scale=64, train_wall=11, gb_free=12.7, wall=604
2022-04-18 21:47:03 - progress_bar.py[line:274] - INFO: epoch 001:    501 / 70844 loss=3.913, loss_v1=0, loss_v2=0, nll_loss=1.869, ntokens=99.3, nsentences=8, sample_size=99.3, sample_size_v1=0, sample_size_v2=0, ppl=3.65, wps=92.4, ups=0.93, wpb=99.3, bsz=8, num_updates=500, lr=2.94083e-07, gnorm=10.402, clip=100, loss_scale=64, train_wall=11, gb_free=12.7, wall=615
2022-04-18 21:47:03 - train.py[line:436] - INFO: begin validation on "valid" subset
slice_id 0 seek offset 0
slice_id 1 seek offset 2500
slice_id 1 seek offset 2500
slice_id 0 seek offset 0
Traceback (most recent call last):
  File "../../train.py", line 528, in <module>
    cli_main()
  File "../../train.py", line 521, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/data1/cxy/OFA/fairseq/fairseq/distributed/utils.py", line 374, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/data1/cxy/OFA/fairseq/fairseq/distributed/utils.py", line 348, in distributed_main
    main(cfg, **kwargs)
  File "../../train.py", line 190, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "../../train.py", line 316, in train
    cfg, trainer, task, epoch_itr, valid_subsets, end_of_epoch
  File "../../train.py", line 402, in validate_and_save
    valid_losses = validate(cfg, trainer, task, epoch_itr, valid_subsets)
  File "../../train.py", line 472, in validate
    trainer.valid_step(sample)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data1/cxy/OFA/trainer.py", line 1059, in valid_step
    sample, self.model, self.criterion, **extra_kwargs
  File "/data1/cxy/OFA/tasks/mm_tasks/caption.py", line 139, in valid_step
    hyps, refs = self._inference(self.sequence_generator, sample, model)
  File "/data1/cxy/OFA/tasks/mm_tasks/caption.py", line 230, in _inference
    gen_out = self.inference_step(generator, [model], sample)
  File "/data1/cxy/OFA/fairseq/fairseq/tasks/fairseq_task.py", line 518, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data1/cxy/OFA/models/sequence_generator.py", line 207, in generate
    return self._generate(models, sample, **kwargs)
  File "/data1/cxy/OFA/models/sequence_generator.py", line 480, in _generate
    assert step < max_len, f"{step} < {max_len}"
AssertionError: 16 < 16
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/miniconda3/envs/pytorch-zme/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda3/envs/pytorch-zme/bin/python3', '-u', '../../train.py', '--local_rank=1', '../../dataset/caption_data/caption_stage1_train.tsv,../../dataset/caption_data/caption_val.tsv', '--selected-cols=0,4,2', '--bpe-dir=../../utils/BPE', '--user-dir=../../ofa_module', '--restore-file=../../checkpoints/ofa_large.pt', '--reset-optimizer', '--reset-dataloader', '--reset-meters', '--save-dir=./stage1_checkpoints/4_0.06_', '--task=caption', '--arch=ofa_large', '--criterion=adjust_label_smoothed_cross_entropy', '--label-smoothing=0.1', '--batch-size=1', '--update-freq=4', '--encoder-normalize-before', '--decoder-normalize-before', '--share-decoder-input-output-embed', '--share-all-embeddings', '--layernorm-embedding', '--patch-layernorm-embedding', '--code-layernorm-embedding', '--resnet-drop-path-rate=0.0', '--encoder-drop-path-rate=0.1', '--decoder-drop-path-rate=0.1', '--dropout=0.1', '--attention-dropout=0.0', '--weight-decay=0.01', '--optimizer=adam', '--adam-betas=(0.9,0.999)', '--adam-eps=1e-08', '--clip-norm=1.0', '--lr-scheduler=polynomial_decay', '--lr=1e-5', '--max-epoch=4', '--warmup-ratio=0.06', '--log-format=simple', '--log-interval=10', '--fixed-validation-seed=7', '--no-epoch-checkpoints', '--keep-best-checkpoints=1', '--save-interval=1', '--validate-interval=1', '--save-interval-updates=500', '--validate-interval-updates=500', '--eval-cider', '--eval-cider-cached-tokens=../../dataset/caption_data/cider_cached_tokens/coco-valid-words.p', '--eval-args={"beam":5,"max_len_b":16,"no_repeat_ngram_size":3}', '--best-checkpoint-metric=cider', '--maximize-best-checkpoint-metric', '--max-src-length=80', '--max-tgt-length=20', '--find-unused-parameters', '--freeze-encoder-embedding', '--freeze-decoder-embedding', '--add-type-embedding', '--scale-attn', '--scale-fc', '--scale-heads', '--disable-entangle', '--num-bins=1000', '--patch-image-size=480', '--drop-worst-ratio=0.2', '--drop-worst-after=2500', '--fp16', '--fp16-scale-window=512', '--num-workers=0']' returned non-zero exit status 1.

**Comment by logicwong** [comment] 2022-04-20 07:56
Duplicate of [#28](https://github.com/OFA-Sys/OFA/issues/28)
You can directly set `--freeze-resnet` to freeze the inner states of batch normalization, or increase the batch_size.

**Closed** 2022-04-25 04:16 UTC
